### ISSUE TITLE
making or listing .md deadlinked files

### ISSUE THREAD

**Issue by prmadev** [tobiaswuerth/obsidian-tools#1]
It would be great if it was possible for the cleanup function to list the deadlinks, or if they are referring to a .md file in the vault, it makes the file in a directory. This way one can see what notes they wanted to make based on their other notes.

**Comment by tobiaswuerth** [comment]
Hi, thanks for the suggestion!

Let me see if I understand this correct.
What you are looking for is
1. an option to print all dead links, including the file they are found in
2. an option to create all dead links, e.g. `..\obsidian-tools\MyTopic.md`

Is this right?

**Comment by prmadev** [comment]
Yes exactly!

**Comment by tobiaswuerth** [comment]
Hi @amirography, I came around to make some improvements in [the new release](https://github.com/tobiaswuerth/obsidian-tools/releases/tag/v0.2). 

I added new plugins which support `--list-dead` and `--create-dead`.
Hope this is what you were looking for
