### ISSUE TITLE
--list-dead lists some existing files

### ISSUE THREAD

**Issue by prmadev** [tobiaswuerth/obsidian-tools#3]
Thank you very much for implementing this function. I really really appreciate it. 
For some reason when I run the script, the list it gives me, also includes some existing files, which existed prior to running the script (so they probebly exist in obsidian index). I have not managed to find a common property in them. 
![Untitled Project](https://user-images.githubusercontent.com/28535608/93577256-111f1a00-f9b1-11ea-8246-d482d797fdcd.gif)
Again, thanks a lot!

```
PS H:\Dropbox\PARA\new> H:\Para_experiment_20200918123820\PARA\Obsidiantools\ch.wuerth.tobias.ObsidianTools.exe H:\Dropbox\PARA --list-dead
Starting plugin: List all dead links
===========================================
Searching for dead links...
Loading files into memory...
Files loaded
Searching for dead links done
Creating result file done, you can find it here: obsidiantools-output-dead-20200918-131026.md
===========================================
Finished plugin: List all dead links
```

**Comment by tobiaswuerth** [comment]
Hi @amirography, you are very welcome, thanks for the suggestion and for reporting this issue! I plan to further improve the tool, so if you have any further inputs feel free to open a ticket anytime :)
 
I'm not exactly sure either what might cause your issue. Do you have the files in a subdirectory? Would it bei possible for you to provide me with a sample vault to reproduce the issue?

- Tobias

**Comment by tobiaswuerth** [comment]
@amirography Hi, I hope you are doing well. 
I've been looking into this issue again and I'm unable to reproduce this behavior at the moment.
I'll hopefully do a v0.3 release soon. 
Feel free to reopen an issue for this, if it isn't fixed.
